### ISSUE TITLE
Unhandled SyntaxKind: ImportClause

### ISSUE THREAD

**Issue by EgoBrainProgrammer** [spinlud/sequelize-typescript-generator#39]
I'm getting error when trying to generate models: **Unhandled SyntaxKind: ImportClause**

`stg -D mysql -h localhost -p 3306 -d warfare2 -u root -x pwdpwd --indices --case camel --clean -T __efmigrationshistory`

[console output](https://pastebin.com/vHYCZRr2)
[package json](https://pastebin.com/6WBtxVEm)

**Comment by BlackYuzia** [comment]
Suppose the same error but with sqlite

```
npx sequelize-typescript-generator -D sqlite -o ./output -S db.sq3 -g -i
```

```
Cleaning output dir
Processing table wcs
DeprecationWarning: 'createIdentifier' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createImportSpecifier' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createNamedImports' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createImportClause' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createLiteral' has been deprecated since v4.0.0. Use `factory.createStringLiteral`, `factory.createStringLiteralFromNode`, `factory.createNumericLiteral`, `factory.createBigIntLiteral`, `factory.createTrue`, `factory.createFalse`, or the factory supplied by your transformation context instead.      
DeprecationWarning: 'createImportDeclaration' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
Error: Debug Failure. Unhandled SyntaxKind: ImportClause.
    at pipelineEmitWithHintWorker (...\myapp\node_modules\typescript\lib\typescript.js:113075:22)
    at pipelineEmitWithHint (...\myapp\node_modules\typescript\lib\typescript.js:112608:17)
    at pipelineEmitWithComments (...\myapp\node_modules\typescript\lib\typescript.js:116249:13)
    at pipelineEmit (...\myapp\node_modules\typescript\lib\typescript.js:112548:13)
    at emitExpression (...\myapp\node_modules\typescript\lib\typescript.js:112532:13)
    at emitImportDeclaration (...\myapp\node_modules\typescript\lib\typescript.js:114492:13)
    at pipelineEmitWithHintWorker (...\myapp\node_modules\typescript\lib\typescript.js:112809:32)
    at pipelineEmitWithHint (...\myapp\node_modules\typescript\lib\typescript.js:112608:17)
    at pipelineEmitWithComments (...\myapp\node_modules\typescript\lib\typescript.js:116249:13)
    at pipelineEmit (...\myapp\node_modules\typescript\lib\typescript.js:112548:13) Promise {
  <rejected> Error: Debug Failure. Unhandled SyntaxKind: ImportClause.
      at pipelineEmitWithHintWorker (...\myapp\node_modules\typescript\lib\typescript.js:113075:22)
      at pipelineEmitWithHint (...\myapp\node_modules\typescript\lib\typescript.js:112608:17)
      at pipelineEmitWithComments (...\myapp\node_modules\typescript\lib\typescript.js:116249:13)
      at pipelineEmit (...\myapp\node_modules\typescript\lib\typescript.js:112548:13)
      at emitExpression (.../myapp/node_modules\typescript\lib\typescript.js:112532:13)
      at emitImportDeclaration (...\myapp\node_modules\typescript\lib\typescript.js:114492:13)
      at pipelineEmitWithHintWorker (...\myapp\node_modules\typescript\lib\typescript.js:112809:32)
      at pipelineEmitWithHint (...\myapp\node_modules\typescript\lib\typescript.js:112608:17)
      at pipelineEmitWithComments (...\myapp\node_modules\typescript\lib\typescript.js:116249:13)
      at pipelineEmit (...\myapp\node_modules\typescript\lib\typescript.js:112548:13)
}
```

**Comment by spinlud** [comment]
Hi, it seems there are some breaking changes with the new typescript versions. Please try latest release and see if it fixes your issue. Mind that the latest version of typescript supported is `4.7.4`.

**Comment by spinlud** [comment]
Fixed now!
