### ISSUE TITLE
Unexpected top-level property "exclude"

### ISSUE THREAD

**Issue by coder-free** [spinlud/sequelize-typescript-generator#52]
Hi, I use `sequelize-typescript-generator` library programmatically:
`sequelize-generator.ts`:

```
import { IConfig, ModelBuilder, DialectMySQL } from 'sequelize-typescript-generator';

(async () => {
    const config: IConfig = {
        connection: {
            dialect: 'mysql',
            database: 'myDatabase',
            username: 'myUsername',
            password: 'myPassword'
        },
        metadata: {
            indices: true,
            case: 'CAMEL',
        },
        output: {
            clean: true,
            outDir: 'models'
        },
        strict: true,
    };

    const dialect = new DialectMySQL();

    const builder = new ModelBuilder(config, dialect);

    try {
        await builder.build();
    }
    catch(err) {
        console.error(err);
        process.exit(1);
    }    
})();
```
I run the typescript file with npm scripts:
`package.json`:
```
{
  ......
  "scripts": {
    ......
    "sequelize-generator": "ts-node sequelize-generator/sequelize-generator.ts",
    ......
  },
  ......
}
```

Then I got this error (But the model file generate success) :
```
Error: ESLint configuration in .eslintrc.js is invalid:
        - Unexpected top-level property "exclude".
```

My `.eslintrc.js` is:
```
module.exports = {
    ......
    exclude: ["node_modules", "dist"]
};

```

**Comment by spinlud** [comment]
Hi, please try latest version `10.0.0` and let me know 🙂

**Comment by coder-free** [comment]
Hi, @spinlud . I got same error:
```
......
Generated index file at src/models-generator/index.ts
Linting files
Error: ESLint configuration in .eslintrc.js is invalid:
        - Unexpected top-level property "exclude".

    at ConfigValidator.validateConfigSchema (/Users/zbf/Desktop/xl/snow-account/snow-account-server/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:272:19)
    at ConfigArrayFactory._normalizeConfigData (/Users/zbf/Desktop/xl/snow-account/snow-account-server/node_modules/@eslint/eslintrc/lib/config-array-factory.js:673:19)
    at ConfigArrayFactory.loadInDirectory (/Users/zbf/Desktop/xl/snow-account/snow-account-server/node_modules/@eslint/eslintrc/lib/config-array-factory.js:541:33)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/zbf/Desktop/xl/snow-account/snow-account-server/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:392:46)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/zbf/Desktop/xl/snow-account/snow-account-server/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:411:20)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/zbf/Desktop/xl/snow-account/snow-account-server/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:411:20)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/Users/zbf/Desktop/xl/snow-account/snow-account-server/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:313:18)
    at FileEnumerator._iterateFilesRecursive (/Users/zbf/Desktop/xl/snow-account/snow-account-server/node_modules/eslint/lib/cli-engine/file-enumerator.js:450:49)
    at _iterateFilesRecursive.next (<anonymous>)
    at FileEnumerator.iterateFiles (/Users/zbf/Desktop/xl/snow-account/snow-account-server/node_modules/eslint/lib/cli-engine/file-enumerator.js:299:49)

```

**Comment by spinlud** [comment]
Closing as resolved in v13.

The code-generation pipeline no longer auto-discovers or loads the host project's ESLint config. v13 lints the generated files with an isolated, bundled ESLint 10 flat config (`overrideConfigFile: true` plus a self-supplied base config), so keys from your project's `.eslintrc` (such as `exclude`) can no longer reach the linter and trigger `Unexpected top-level property`.

If you still hit a linting error on the latest release, please open a new issue with the version and a minimal repro.
